services:

  client.api:
    image: saifdev22/blazor-wasm
    container_name: Starter.Blazor
    build:
      context: .
      dockerfile: src/api/Client.API/Dockerfile
    ports:
      - 6050:8080
      - 6070:8081
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:8080
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
