services:  

  mssql.database:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: Starter.SQLServer
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=25122000SK
      - MSSQL_PID=Express  
      - MSSQL_DATABASE=TestDB
      - MSSQL_MEMORY_LIMIT_MB=512 
    restart: always
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql 
    networks:
      - mynetwork
      
  postgres.database:
    image: postgres:17
    container_name: Starter.PostgreSQL
    environment:
      - POSTGRES_DB=test-db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - mynetwork
       
  redis.database:
    image: redis:latest
    container_name: Starter.Redis
    restart: always
    ports:
      - 6379:6379
    networks:
      - mynetwork
    volumes:
      - redis_data:/data
 
  rabbit.mq:
    image: rabbitmq:4.1-rc-management-alpine
    container_name: Starter.RabbitMQ
    hostname: starter-rabbitmq
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq
        - rabbitmq_log:/var/log/rabbitmq
    environment:
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
    ports:
      - 5672:5672
      - 15672:15672
    restart: always
 
 
  seq.logging:
    image: datalust/seq:latest
    container_name: Starter.Seq
    environment:
      - ACCEPT_EULA=Y
    ports:
      - 5341:5341
      - 8081:80
 
  jaeger.tracing:
    image: jaegertracing/all-in-one:latest
    container_name: Starter.Jaeger
    ports:
      - 4317:4317
      - 4318:4318
      - 16686:16686
 
volumes:
  sqlserver_data:
  postgres_data:
  redis_data:
  rabbitmq_data:
  rabbitmq_log:

networks:
  mynetwork:
    name: starter.network 
    driver: bridge
